# -*- coding: utf-8 -*-
"""Normalized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ybYaBzT_cNSgswCV2-eCp7zLhcy6MYr-

# 정규화 코드
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("train_activity.csv.part0")  # 파일명은 실제 업로드한 파일명에 맞게 수정

# 정규화할 열 지정
columns_to_scale =
 [
    'activity_score',
    'activity_steps',
    'activity_inactive',
    'activity_high',
    'activity_score_meet_daily_targets',
    'activity_score_move_every_hour',
    'activity_daily_movement',
    'activity_total'
]

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df[columns_to_scale])
scaled_df = pd.DataFrame(scaled_data, columns=columns_to_scale)

for col in columns_to_scale:
    df[col] = scaled_df[col]

print(df.head())
print(df['activity_total'].head(20))

df.to_csv("normalized_result.csv", index=False)
files.download("normalized_result.csv")
